language: node_js

node_js:
  - "node"

services:
  - docker

script:
  - cd frontend
  - npm install
  - npm run build:sass
  - npm run build
  - cd ../backend
  - npm install
  - cd ../
  - docker build -t app .
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-2)
  - docker tag app:latest $AWS_ECR_PATH
  - docker push $AWS_ECR_PATH

branches:
  only:
    - master
    - stable
