language: node_js

node_js:
  - "10"

services:
  - docker

script:
  - cd frontend || travis_terminate 1
  - npm install || travis_terminate 1
  - npm run build:sass || travis_terminate 1
  - npm run build || travis_terminate 1
  - cd ../backend || travis_terminate 1
  - npm install || travis_terminate 1
  - cd ../ || travis_terminate 1
  - docker build -t app . || travis_terminate 1
  - pip install --user awscli || travis_terminate 1
  - export PATH=$PATH:$HOME/.local/bin || travis_terminate 1
  - eval $(aws ecr get-login --region us-east-2 --no-include-email) || travis_terminate 1
  - docker tag app:latest $AWS_ECR_PATH || travis_terminate 1
  - docker push $AWS_ECR_PATH || travis_terminate 1

branches:
  only:
    - master
    - stable
